# This is a basic workflow to help you get started with Actions

name: HTML5 Build CI

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build: [release, debug]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install hscript --quiet
          haxelib --never install flixel --quiet
          haxelib install flixel-addons --quiet
          echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build html5 -${{ matrix.build }} -clean -D no-compilation -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          if [ "${{ matrix.build }}" == final]; then
          name: build-final
          path: export/release/html5/bin
          else
          name: build-${{ matrix.build }}
          path: export/${{ matrix.build }}/html5/bin
          fi
