# This is a basic workflow to help you get started with Actions

name: HTML5 Build CI

# Controls when the workflow will run
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build: [release, debug]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.1.1 > /dev/null
          haxelib install lime 7.8.0 --quiet
          haxelib git openfl https://github.com/mcagabe19/fastfl-9.0.2.git
          haxelib --never install flixel 4.8.1 --quiet
          haxelib install flixel-addons 2.9.0 --quiet
          echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build html5 -${{ matrix.arch }} -D no-compilation -D macro-times -D analyzer-optimize --app-version="4.0.0-${{ github.run_id}}"

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-${{ matrix.arch }}
          path: export/${{ matrix.arch }}/html5/bin
