name: HTML5 Build CI

on: [workflow_dispatch]

jobs:
  html5:
    name: HTML5
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        version: [20.04]
        build: [release, debug]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.9.0.git --quiet
          haxelib install flixel-addons 2.11.0 --quiet
      - name: Compile
        run: haxelib run lime build html5 -D no-compilation -D macro-times -D analyzer-optimize
      - name: help me
        run: ls
      # - name: Publish Artifact
        # uses: actions/upload-artifact@main
        # with:
          # name: build-ubuntu${{ matrix.version }}-${{ matrix.build }}
          # path: 'export/${{ matrix.build }}/html5/bin'
      # - name: Publish Artifact (Only JS)
        # uses: actions/upload-artifact@main
        # with:
          # name: onlyjs-ubuntu${{ matrix.version }}-${{ matrix.build }}
          # path: 'export/${{ matrix.build }}/html5/bin/*.js*'
